# Generated by Django 3.1.5 on 2021-01-26 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bakery', '0002_bakeryitem_bakeryitemingredient_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bakeryingredient',
            name='available_quantity',
            field=models.FloatField(),
        ),
    ]
